// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlow.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("TechQA task")]
    public partial class TechQATaskFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Task1.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "TechQA task", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1 home page opens and loads")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _1HomePageOpensAndLoads()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1 home page opens and loads", null, new string[] {
                        "web"});
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 testRunner.Given("I can open visma home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.When("home page title check", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 and 3.1 3.3 presentation request page all marked required fields are required")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _2And3_13_3PresentationRequestPageAllMarkedRequiredFieldsAreRequired()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 and 3.1 3.3 presentation request page all marked required fields are required", null, new string[] {
                        "web"});
#line 11
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 16
 testRunner.Given("I can open visma home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.Then("accept cookies", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
 testRunner.Then("open presentation request form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.Then("0 X errors are present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "formmodel"});
            table1.AddRow(new string[] {
                        "{ \'Name\':\'name\', \'Surname\':\'surname\', \'Company\':\'company\', \'Email\':\'xx@xx.xx\', \'P" +
                            "hone\':\'phone\', \'GDPR\':false }"});
#line 20
 testRunner.Then("I fill in the following form", ((string)(null)), table1, "Then ");
#line 23
 testRunner.Then("click form submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
 testRunner.Then("1 X errors are present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
 testRunner.Then("clear presentation request form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "formmodel"});
            table2.AddRow(new string[] {
                        "{ \'Name\':null, \'Surname\':null, \'Company\':null, \'Email\':null, \'Phone\':null, \'GDPR\'" +
                            ":true }"});
#line 26
 testRunner.Then("I fill in the following form", ((string)(null)), table2, "Then ");
#line 29
 testRunner.Then("click form submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
 testRunner.Then("5 X errors are present", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3.3 Language select change page language and domain")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("xx@xxxx", null)]
        [NUnit.Framework.TestCaseAttribute("a\"b(c)d,e:f;g<h>i[j\\k]l@xx.xx", null)]
        [NUnit.Framework.TestCaseAttribute("xx@xx@xx.xx", null)]
        [NUnit.Framework.TestCaseAttribute("xx\"xx\"xx@xx.xx", null)]
        [NUnit.Framework.TestCaseAttribute("xx xx\"xx\\xx@xx.xx", null)]
        [NUnit.Framework.TestCaseAttribute("xx\\ xx\\\"xx\\xx@xx.xx", null)]
        [NUnit.Framework.TestCaseAttribute("xx..xx@xx.xx", null)]
        [NUnit.Framework.TestCaseAttribute("xx@xx..xx", null)]
        [NUnit.Framework.TestCaseAttribute("1234567890123456789012345678901234567890123456789012345678901234x+x@xx.xx", null)]
        [NUnit.Framework.TestCaseAttribute("alskjnakjanv1wadfqaebbsfdfagfbnbKJANDVlvn13dcljnvzlkjbnadlkgf3cjnj@xx.xx", null)]
        public virtual void _3_3LanguageSelectChangePageLanguageAndDomain(string invalidEmail, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3.3 Language select change page language and domain", null, @__tags);
#line 33
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 37
 testRunner.Given("I can open visma home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
 testRunner.Then("open presentation request form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
 testRunner.Then(string.Format("{0} email should not be accepted", invalidEmail), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4 home page blog opens in a new tab")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _4HomePageBlogOpensInANewTab()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4 home page blog opens in a new tab", null, new string[] {
                        "web"});
#line 60
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 62
 testRunner.Given("I can open visma home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 66
 testRunner.Then("scroll blog element into view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 67
 testRunner.Then("build blog teaser model", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
 testRunner.Then("open every blog record", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("5 visit all social links in footer")]
        [NUnit.Framework.CategoryAttribute("web")]
        public virtual void _5VisitAllSocialLinksInFooter()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5 visit all social links in footer", null, new string[] {
                        "web"});
#line 71
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 73
 testRunner.Given("I can open visma home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 75
 testRunner.Then("scroll social link elements into view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 76
 testRunner.Then("build social links model", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
 testRunner.Then("visit every social link record", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("6 Language select change page language and domain")]
        [NUnit.Framework.CategoryAttribute("web")]
        [NUnit.Framework.TestCaseAttribute("Denmark", "da", ".dk", null)]
        [NUnit.Framework.TestCaseAttribute("Finland", "fi", ".fi", null)]
        [NUnit.Framework.TestCaseAttribute("Latvia", "lv", ".lv", null)]
        [NUnit.Framework.TestCaseAttribute("Lithuania", "lt", ".lt", null)]
        [NUnit.Framework.TestCaseAttribute("Netherlands", "nl", "nl.", null)]
        [NUnit.Framework.TestCaseAttribute("Norway", "nb", ".no", null)]
        [NUnit.Framework.TestCaseAttribute("Romania", "ro", ".ro", null)]
        [NUnit.Framework.TestCaseAttribute("Sweden", "sv", ".se", null)]
        [NUnit.Framework.TestCaseAttribute("UK", "en", ".co.uk", null)]
        [NUnit.Framework.TestCaseAttribute("Visma.com", "en", ".com", null)]
        public virtual void _6LanguageSelectChangePageLanguageAndDomain(string country, string language, string domain, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "web"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("6 Language select change page language and domain", null, @__tags);
#line 80
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 82
 testRunner.Given("I can open visma home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 84
 testRunner.Then("scroll language select element into view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 85
 testRunner.Then(string.Format("footer country select {0}", country), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 86
 testRunner.Then(string.Format("opened page has {0} and url contains {1}", language, domain), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

